### ISSUE TITLE
update opencloudmesh / rd-sram to use master branch of owncloud/core

### ISSUE THREAD

**Issue by michielbdejong** [cs3org/ocm-test-suite#43]
https://github.com/owncloud/core/pull/40886 is merged but https://github.com/pondersource/dev-stock/blob/157c65a/docker/owncloud-opencloudmesh.Dockerfile#L13-L14 still uses our branch.
We should now use the master branch of owncloud/core!

**Comment by MahdiBaghbani** [comment]
It means opencloudmesh no longer needs to manually install its own version of ownCloud and can use the base image for ownCloud like other images
